blank_issues_enabled: true

contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.

newIssueWelcomeComment: >
  Hello there! 👋🏻 Welcome to the IoT-Projects-and-Scripts! 🚀⚡️
  
  Thank you and congrats 🎉 for opening your very first issue in this project. 
  Please adhere to our [Code of Conduct](https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/CODE_OF_CONDUCT). 👍🏻
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/.github/pullrequest_template.md).
  
  Feel free to get in touch with me through social media handles. Hope to see you there!😄
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there! 👋 Welcome to the project! 💖
  
  Thank you and congrats 🎉 for opening your first pull request. 
  Please adhere to our [Code of Conduct](https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/CODE_OF_CONDUCT). 🙌🏻 We will get back to you as soon as we can. 😄
   
  Feel free to get in touch with me through social media handles. Hope to see you there!😄
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first Pull Request! 🎉 All the best for your amazing open source journey ahead. 🚀⚡️
